# This is a basic workflow that is manually triggered
name: TestPROGPOE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # List contents of the directory
      - name: List contents
        run: ls

      # Compiles classes to test
      - name: Compile classes
        working-directory: ./src/PROG5121_POE
        run: javac -cp "../../testresources/junit-platform-console-standalone-1.8.2.jar" Prog5121_poe.java LogIn.java Registration.java Tasks.java ../../test/PROG5121_POE/LogInTest.java ../../test/PROG5121_POE/RegistrationTest.java ../../test/PROG5121_POE/TasksTest.java

      # List contents of src to verify that classes compiled
      - name: List contents of src directory after compile
        working-directory: ./src/PROG5121_POE
        run: ls

      # Copy compiled classes to test directory
      - name: Copy compiled classes to testresources directory
        working-directory: ./src/PROG5121_POE
        run: cp -t ../../test/PROG5121_POE Prog5121_poe.class LogIn.class Registration.class Tasks.class

      # Copy compiled tests
      - name: Copy compiled Test classes to testresources directory
        working-directory: ./test/PROG5121_POE
        run: cp -t ../../testresources/ LogInTest.class RegistrationTest.class TasksTest.class

      # List contents of test package
      - name: List contents test package
        working-directory: ./test/PROG5121_POE
        run: ls

      # Run tests and output report
      - name: Run tests and create report
        working-directory: ./test
        run: java -cp "../testresources/junit-platform-suite-commons-1.8.2.jar:../testresources/junit-platform-suite-api-1.8.2.jar:../testresources/junit-platform-suite-engine-1.8.2.jar:../testresources/junit-jupiter-engine-5.8.2.jar:../testresources/junit-platform-console-standalone-1.8.2.jar:." org.junit.platform.console.ConsoleLauncher --select-class TasksTest --reports-dir "reports"
